config/routes.rb
Rails.application.routes.draw do
  get 'occurrences/show'

  get 'activities/new'

  root to: "home#index"

  devise_for :users

  resource :activities
  resource :occurrences
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user

  has_many :occurrences
end

app/models/occurrence.rb
class Occurrence < ActiveRecord::Base
  belongs_to :activity
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
  has_many :occurrences, through: :activities

  def google_ical_url
    "https://www.google.com/calendar/ical/ncwjohnstone%40gmail.com/private-1608baa517370be96acbc6f807f79e4d/basic.ics"
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def show
    @activities = current_user.activities
  end

  def new
    @activity = Activity.new
  end

  def create
    CreateActivity.new(current_user, allowed_creation_params).run
    redirect_to '/activities' # TODO - use a path helper
  end

  private

  def allowed_creation_params
    params.require(:activity).permit(
      :name,
      :minimum_duration,
      :maximum_duration,
      :desired_amount,
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController
  def show
    render json: FetchGoogleCalendar.new(current_user).get.map(&:to_json)
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/occurrences_helper.rb
module OccurrencesHelper
end

app/views/activities/_activity.html.erb
<div class="activity">
  <h3><%= activity.name %></h3>
  <p>
    Duration: <%= activity.minimum_duration %> to <%= activity.maximum_duration %> minutes
  </p>
  <p>
    Desired amount per week: <%= activity.desired_amount %> minutes
  </p>
</div>

app/views/activities/new.html.erb
<h1>Create new Activity</h1>

<%= simple_form_for @activity, url: {action: :create} do |f| %>
  <%= f.input :name %>
  <%= f.input :minimum_duration %>
  <%= f.input :maximum_duration %>
  <%= f.input :desired_amount %>
  <%= f.button :submit %>
<% end %>

app/views/activities/show.html.erb
<h1>Activities</h1>

<%= link_to 'New Activity', new_activities_path %>

<%= render @activities %>
<div id='calendar'></div>

app/views/home/index.html.erb
<h1>Time Ninja</h1>

<%= link_to 'Log in', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeNinja</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</body>
</html>

app/views/occurrences/show.html.erb
<h1>Occurrences#show</h1>
<p>Find me in app/views/occurrences/show.html.erb</p>